// kernel::vault_sourcing — sourcing inbox triage routine.
//
// (ADR-002 substrate § vault v1 §8.4 sourcing-workflow, 2026-06-01 —
// memory `decision_vault_adr_002_section_8`.)
//
// Reads `vault/sourcing/*.md`, classifies each item heuristically
// (frontmatter passthrough + first-line title guess), and writes a
// structured review-queue file at `vault/.ctrl/review-queue/<date>.md`
// matching the schema in `vault/.ctrl/sourcing-prompt.md`.
//
// This is the kernel-side seed routine. The richer LLM-backed flow
// lives inside the Irisy agent — kernel only ships the deterministic
// "list, suggest path under notes/, copy tags" pass so the loop works
// before Irisy attaches.
//
// Triggered three ways per §8.4 (S1, all concurrent):
//   1. cron — kernel tokio interval (placeholder, calls run() on tick)
//   2. count threshold — vault_watch emits create events, command
//      `vault_sourcing_count_pending()` reports inbox size for the
//      frontend's poll
//   3. manual — user calls vault_sourcing_run from the chat / L2

use std::collections::HashSet;
use std::path::Path;

use serde::Serialize;
use serde_json::Value;

use crate::kernel::vault;

#[derive(Debug, Serialize)]
pub struct SourcingRunReport {
    pub review_path: String,
    pub items_processed: usize,
    pub skipped_already_indexed: usize,
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum SourcingError {
    #[error("sourcing: {0}")]
    Vault(String),
    #[error("sourcing: review queue write failed: {0}")]
    Write(String),
}

/// Iterate the inbox and rewrite the review-queue file for the
/// requested date. The routine is idempotent: an existing queue file
/// is overwritten in full so multiple runs in a single day converge
/// on the same output.
pub fn run(vault_root: &Path, date_yyyy_mm_dd: &str) -> Result<SourcingRunReport, SourcingError> {
    let inbox = vault::list(vault_root, Some("sourcing"))
        .map_err(|e| SourcingError::Vault(e.to_string()))?;

    let review_rel = format!(".ctrl/review-queue/{date_yyyy_mm_dd}.md");
    let mut items_processed = 0usize;
    let mut skipped_already_indexed = 0usize;

    let mut body = String::new();
    body.push_str(&format!(
        "# Sourcing review — {date_yyyy_mm_dd}\n\nGenerated by the kernel sourcing routine.\nApply or discard each item from the Sourcing Review tab.\n\n",
    ));

    // Pre-compute existing target paths once so we don't suggest a
    // path that would collide with an existing note.
    let all_notes: HashSet<String> = vault::list(vault_root, None)
        .map(|v| v.into_iter().collect())
        .unwrap_or_default();

    for sourcing_rel in inbox.iter() {
        if !sourcing_rel.ends_with(".md") {
            continue;
        }
        // Skip pinned items the user marked "keep"
        let entry = match vault::read(vault_root, sourcing_rel) {
            Ok(e) => e,
            Err(e) => {
                tracing::warn!(path = %sourcing_rel, error = %e, "sourcing: read failed");
                continue;
            }
        };
        if entry
            .frontmatter
            .get("integrated")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
        {
            skipped_already_indexed += 1;
            continue;
        }

        let kind = classify(&entry.content, &entry.frontmatter);
        let suggest = suggest_target_path(sourcing_rel, &entry.content, &all_notes);
        let proposal_fm = build_proposal_frontmatter(&entry.frontmatter, &kind);
        let backlinks = derive_backlinks(&entry.content, &all_notes);

        body.push_str(&format!("## {sourcing_rel}\n"));
        body.push_str(&format!("- **type**: {kind}\n"));
        body.push_str(&format!("- **suggest path**: `{suggest}`\n"));
        body.push_str("- **frontmatter**:\n");
        body.push_str("```\n");
        body.push_str(&proposal_fm);
        if !proposal_fm.ends_with('\n') {
            body.push('\n');
        }
        body.push_str("```\n");
        if !backlinks.is_empty() {
            body.push_str(&format!(
                "- **backlinks**: {}\n",
                backlinks
                    .iter()
                    .map(|b| format!("`{b}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        body.push_str("- **actions**: [Accept] [Edit] [Reject]\n\n");

        items_processed += 1;
    }

    let fm = serde_json::json!({
        "type": "sourcing-review",
        "date": date_yyyy_mm_dd,
        "items": items_processed,
    });
    vault::write(vault_root, &review_rel, &body, &fm)
        .map_err(|e| SourcingError::Write(e.to_string()))?;

    Ok(SourcingRunReport {
        review_path: review_rel,
        items_processed,
        skipped_already_indexed,
    })
}

/// Count items in the inbox — frontend uses this to drive the L2
/// "Review (N)" badge without spawning a full run on every render.
pub fn count_pending(vault_root: &Path) -> usize {
    vault::list(vault_root, Some("sourcing"))
        .map(|v| v.iter().filter(|p| p.ends_with(".md")).count())
        .unwrap_or(0)
}

// ---------- heuristics ----------

fn classify(content: &str, frontmatter: &Value) -> String {
    if let Some(kind) = frontmatter.get("type").and_then(|v| v.as_str()) {
        return kind.to_string();
    }
    if let Some(source) = frontmatter.get("source").and_then(|v| v.as_str()) {
        return source.to_string();
    }
    if content.contains("```") {
        return "code-snippet".to_string();
    }
    if content
        .lines()
        .next()
        .map(|l| l.starts_with("http://") || l.starts_with("https://"))
        .unwrap_or(false)
    {
        return "link".to_string();
    }
    if content.chars().count() < 280 {
        return "fleeting-note".to_string();
    }
    "draft".to_string()
}

fn suggest_target_path(
    sourcing_rel: &str,
    content: &str,
    all_notes: &HashSet<String>,
) -> String {
    let stem_title = content
        .lines()
        .find(|l| !l.trim().is_empty())
        .map(|l| slugify(l.trim().trim_start_matches('#').trim()))
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| {
            sourcing_rel
                .rsplit('/')
                .next()
                .unwrap_or(sourcing_rel)
                .trim_end_matches(".md")
                .to_string()
        });

    let mut candidate = format!("notes/inbox/{stem_title}.md");
    let mut suffix = 2;
    while all_notes.contains(&candidate) {
        candidate = format!("notes/inbox/{stem_title}-{suffix}.md");
        suffix += 1;
    }
    candidate
}

fn build_proposal_frontmatter(original: &Value, kind: &str) -> String {
    let mut map = serde_json::Map::new();
    if let Some(obj) = original.as_object() {
        for (k, v) in obj {
            // Strip transient sourcing-only fields — `integrated`
            // belongs to the inbox semantics, not the destination
            // note.
            if k == "integrated" {
                continue;
            }
            map.insert(k.clone(), v.clone());
        }
    }
    map.entry("type".to_string())
        .or_insert(Value::String(kind.to_string()));
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    map.entry("sourced_at".to_string())
        .or_insert(Value::Number(now_ms.into()));
    serde_json::to_string_pretty(&Value::Object(map)).unwrap_or_default()
}

fn derive_backlinks(content: &str, all_notes: &HashSet<String>) -> Vec<String> {
    // Cheap "did the user mention a known note by stem" pass — anything
    // smarter requires embedding similarity which lives in Irisy.
    let mut hits: Vec<String> = Vec::new();
    for note in all_notes.iter() {
        if note.starts_with(".ctrl/") || note.starts_with("sourcing/") {
            continue;
        }
        let stem = note
            .rsplit('/')
            .next()
            .unwrap_or(note)
            .trim_end_matches(".md");
        if stem.len() < 3 {
            continue;
        }
        if content.contains(stem) {
            hits.push(note.clone());
            if hits.len() >= 3 {
                break;
            }
        }
    }
    hits
}

fn slugify(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_was_dash = false;
    for ch in s.chars() {
        if ch.is_alphanumeric() {
            out.extend(ch.to_lowercase());
            last_was_dash = false;
        } else if !last_was_dash && !out.is_empty() {
            out.push('-');
            last_was_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        if let Some(parent) = p.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(p, body).unwrap();
    }

    #[test]
    fn run_emits_review_queue_with_items() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        // Pre-create sourcing inbox + an inbox dir for write_index to be
        // happy. Vault init happens only in ensure_vault_layout; tests
        // bypass that.
        fs::create_dir_all(root.join("sourcing")).unwrap();
        fs::create_dir_all(root.join("notes")).unwrap();
        write(
            root,
            "sourcing/a.md",
            "---\nsource: clipboard\n---\n\nA short captured note about Rust patterns.\n",
        );
        let report = run(root, "2026-06-01").unwrap();
        assert_eq!(report.items_processed, 1);
        let queue_path = root.join(".ctrl/review-queue/2026-06-01.md");
        let contents = fs::read_to_string(&queue_path).unwrap();
        assert!(contents.contains("## sourcing/a.md"));
        assert!(contents.contains("[Accept] [Edit] [Reject]"));
    }

    #[test]
    fn count_pending_counts_md_only() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join("sourcing")).unwrap();
        write(root, "sourcing/a.md", "---\n---\n\nfoo");
        write(root, "sourcing/b.md", "---\n---\n\nbar");
        write(root, "sourcing/notes.txt", "ignore me");
        assert_eq!(count_pending(root), 2);
    }

    #[test]
    fn classify_recognises_code_snippet() {
        let v = serde_json::json!({});
        assert_eq!(classify("```rs\nfn x(){}\n```", &v), "code-snippet");
    }
}
