#!/usr/bin/env node
// Regenerate .olym/handoffs/INDEX.md from H-*.md frontmatter.
//
// Reads every `H-YYYY-MM-DD-NNN-*.md` under .olym/handoffs/, parses the
// YAML frontmatter (status / severity / assigned_to / lane / project_id /
// category / title / updated), and writes a fresh INDEX.md grouped by
// status, lane, project, and category.
//
// Intentionally dependency-free — uses naive YAML scanning, only the
// scalar fields we care about. If a future handoff uses a complex YAML
// shape this script will need to grow.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const HANDOFF_DIR = path.join(REPO_ROOT, '.olym', 'handoffs');
const OUTPUT = path.join(HANDOFF_DIR, 'INDEX.md');

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/;
const HANDOFF_FILE_RE = /^H-\d{4}-\d{2}-\d{2}-\d{3}.*\.md$/;

const STATUS_ORDER = ['open', 'claimed', 'in_progress', 'done', 'verified', 'wontfix', 'archived'];
const ACTIVE_STATUSES = new Set(['open', 'claimed', 'in_progress']);

const STATUS_LABELS = {
  open: 'Open',
  claimed: 'Claimed',
  in_progress: 'In Progress (claimed / in_progress)',
  done: 'Done (awaiting verification)',
  verified: 'Verified',
  wontfix: "Won't Fix",
  archived: 'Archived',
};

function parseScalar(raw) {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) return trimmed.slice(1, -1);
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) return trimmed.slice(1, -1);
  return trimmed;
}

function parseFrontmatter(text) {
  const match = text.match(FRONTMATTER_RE);
  if (!match) return null;
  const body = match[1];
  const fields = {};
  const lines = body.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('  ') || line.startsWith('\t')) continue; // skip list items / nested
    const colonIdx = line.indexOf(':');
    if (colonIdx < 0) continue;
    const key = line.slice(0, colonIdx).trim();
    const value = parseScalar(line.slice(colonIdx + 1));
    if (key) fields[key] = value;
  }
  return fields;
}

function loadHandoffs() {
  if (!fs.existsSync(HANDOFF_DIR)) return [];
  const entries = fs.readdirSync(HANDOFF_DIR);
  const items = [];
  for (const name of entries) {
    if (!HANDOFF_FILE_RE.test(name)) continue;
    const fullPath = path.join(HANDOFF_DIR, name);
    const text = fs.readFileSync(fullPath, 'utf8');
    const fm = parseFrontmatter(text);
    if (!fm || !fm.id) continue;
    items.push({
      id: fm.id,
      title: fm.title ?? '(no title)',
      severity: fm.severity ?? 'P?',
      status: fm.status ?? 'open',
      assigned_to: fm.assigned_to ?? '?',
      lane: fm.lane ?? '?',
      project_id: fm.project_id ?? '(no project)',
      category: fm.category ?? '(uncategorized)',
      updated: fm.updated ?? '',
      file: name,
    });
  }
  items.sort((a, b) => a.id.localeCompare(b.id));
  return items;
}

function fmtLine(h) {
  return `- **[${h.id}](./${h.file})** · [${h.severity}] (${h.status}) · _${h.assigned_to}_ · ${h.title}`;
}

function groupBy(items, key) {
  const groups = new Map();
  for (const item of items) {
    const k = item[key] || '(none)';
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(item);
  }
  return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function buildSection(title, lines) {
  if (lines.length === 0) return `## ${title}\n\n_(none)_\n`;
  return `## ${title}\n\n${lines.join('\n')}\n`;
}

function render(items) {
  const byStatus = Object.fromEntries(STATUS_ORDER.map((s) => [s, []]));
  for (const h of items) {
    if (!byStatus[h.status]) byStatus[h.status] = [];
    byStatus[h.status].push(h);
  }

  const counts = STATUS_ORDER.map((s) => `${s}=${byStatus[s].length}`).join(' · ');

  const active = items.filter((h) => ACTIVE_STATUSES.has(h.status));

  const laneSection = groupBy(active, 'lane')
    .map(([lane, list]) => `### ${lane}\n\n${list.map(fmtLine).join('\n')}\n`)
    .join('\n');

  const projectSection = groupBy(active, 'project_id')
    .map(([proj, list]) => `### ${proj}\n\n${list.map(fmtLine).join('\n')}\n`)
    .join('\n');

  const categorySection = groupBy(active, 'category')
    .map(([cat, list]) => `### ${cat}\n\n${list.map(fmtLine).join('\n')}\n`)
    .join('\n');

  const statusSections = STATUS_ORDER.filter((s) => s !== 'archived')
    .map((s) => buildSection(STATUS_LABELS[s] ?? s, byStatus[s].map(fmtLine)))
    .join('\n');

  return `<!-- AUTO-GENERATED by scripts/handoffs-index.js · do not edit -->

# Handoffs Index

> Auto-generated from \`H-*.md\` frontmatter. Edits are overwritten.

> **Counts** · ${counts}

${statusSections}
## By Lane (active)

${laneSection || '_(no active handoffs)_'}
## By Project (active)

${projectSection || '_(no active handoffs)_'}
## By Category (active)

${categorySection || '_(no active handoffs)_'}
`;
}

function main() {
  const items = loadHandoffs();
  const out = render(items);
  fs.writeFileSync(OUTPUT, out);
  console.log(`wrote ${OUTPUT} · ${items.length} handoffs`);
}

main();
