#!/usr/bin/env node
// handoffs-index — regenerate .olym/handoffs/INDEX.md from H-*.md frontmatter
//
// Usage:
//   node scripts/handoffs-index.js          # write INDEX.md
//   node scripts/handoffs-index.js --check  # exit 1 if INDEX.md drifted (CI)
//   node scripts/handoffs-index.js --stdout # print to stdout, don't write
//
// Reads:  .olym/handoffs/H-*.md  (frontmatter)
// Writes: .olym/handoffs/INDEX.md
//
// Frontmatter schema (per _template.md):
//   id, title, severity, status, reporter, assigned_to, lane, touches, created, updated
//
// Backward compat: also reads legacy `opened_by` / `opened_at` if reporter / created missing.
//
// Sections produced:
//   Open  ·  In Progress (claimed | in_progress)  ·  Done (awaiting verification)
//   Verified  ·  Won't Fix  ·  By Lane  ·  P2 (older free-text section preserved if present in any handoff body)
//
// Spec: .olym/specs/multi-agent-fleet/spec.md §7.5

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, basename, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const HANDOFFS_DIR = join(REPO_ROOT, '.olym', 'handoffs');
const INDEX_PATH = join(HANDOFFS_DIR, 'INDEX.md');

const HEADER = '<!-- AUTO-GENERATED by scripts/handoffs-index.js · do not edit -->';

// ── frontmatter parser (no external dep — handoff frontmatter is simple key: value)

function parseFrontmatter(text) {
  // Trim leading BOM and whitespace
  const trimmed = text.replace(/^\uFEFF/, '');
  const m = trimmed.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const body = m[1];
  const out = {};
  let currentKey = null;
  for (const rawLine of body.split(/\r?\n/)) {
    // Strip yaml comments (only when full-line — values may contain `#`)
    const line = rawLine.replace(/^\s*#.*$/, '');
    if (!line.trim()) continue;
    // List item: leading dash → push onto currentKey if it's an array
    const listMatch = line.match(/^\s+-\s+(.*)$/);
    if (listMatch && currentKey) {
      if (!Array.isArray(out[currentKey])) out[currentKey] = [];
      out[currentKey].push(stripQuotes(listMatch[1].trim()));
      continue;
    }
    // key: value
    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*)$/);
    if (kvMatch) {
      const key = kvMatch[1];
      const value = stripQuotes(kvMatch[2].trim());
      if (value === '') {
        out[key] = []; // empty → assume list to follow
        currentKey = key;
      } else {
        out[key] = value;
        currentKey = null;
      }
    }
  }
  return out;
}

function stripQuotes(s) {
  if (s.startsWith('"') && s.endsWith('"')) return s.slice(1, -1);
  if (s.startsWith("'") && s.endsWith("'")) return s.slice(1, -1);
  return s;
}

// ── load all handoffs

function loadHandoffs() {
  if (!existsSync(HANDOFFS_DIR)) return [];
  const handoffs = [];
  for (const file of readdirSync(HANDOFFS_DIR)) {
    // Strict id match (H-YYYY-MM-DD-NNN.md) so companion docs like
    // H-2026-06-09-001-ADR-amendments.md don't show up as handoffs.
    if (!/^H-\d{4}-\d{2}-\d{2}-\d{3}\.md$/.test(file)) continue;
    const path = join(HANDOFFS_DIR, file);
    const text = readFileSync(path, 'utf8');
    const fm = parseFrontmatter(text);
    if (!fm) continue;
    // Backward compat
    if (!fm.reporter && fm.opened_by) fm.reporter = fm.opened_by;
    if (!fm.created && fm.opened_at) fm.created = fm.opened_at;
    handoffs.push({ file, ...fm });
  }
  // Sort by id (lex order — id format is H-YYYY-MM-DD-NNN so this is chronological)
  handoffs.sort((a, b) => (a.id || a.file).localeCompare(b.id || b.file));
  return handoffs;
}

// ── G-009 (H-2026-05-05-009): handoff ID collision detection (active + archive)

import { statSync } from 'node:fs';

function loadAllHandoffsRecursive(dir) {
  // Walk dir + sub-dirs (e.g., _archive/2026-04/, _archive/2026-05/)
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    let stat;
    try { stat = statSync(path); } catch { continue; }
    if (stat.isDirectory()) {
      out.push(...loadAllHandoffsRecursive(path));
    } else if (entry.startsWith('H-') && entry.endsWith('.md')) {
      const text = readFileSync(path, 'utf8');
      const fm = parseFrontmatter(text);
      if (!fm) continue;
      out.push({ file: relative(REPO_ROOT, path).replace(/\\/g, '/'), id: fm.id || null });
    }
  }
  return out;
}

function detectCollisions(allHandoffs) {
  const idToFiles = new Map();
  for (const h of allHandoffs) {
    if (!h.id) continue; // skip filename-only id (legacy compat)
    if (!idToFiles.has(h.id)) idToFiles.set(h.id, []);
    idToFiles.get(h.id).push(h.file);
  }
  const collisions = [...idToFiles.entries()].filter(([, files]) => files.length > 1);
  if (collisions.length > 0) {
    console.error('[handoffs-index] COLLISION: handoff ID duplicates detected:');
    for (const [id, files] of collisions) {
      console.error(`  ${id}:`);
      for (const f of files) console.error(`    - ${f}`);
    }
    console.error('[handoffs-index] resolve: rename file or fix frontmatter id, then re-run');
    process.exit(1);
  }
}

// ── render

function rowFor(h) {
  const id = h.id || h.file.replace(/\.md$/, '');
  const link = `[${id}](${h.file})`;
  const sev = h.severity || '?';
  const lane = h.lane || h.assigned_to || '—';
  const assigned = h.assigned_to || '—';
  const title = (h.title || '').replace(/\|/g, '\\|');
  return `| ${link} | ${sev} | ${lane} | →${assigned} | ${title} |`;
}

function tableHeader() {
  return [
    '| ID | Sev | Lane | Assigned | Title |',
    '|---|---|---|---|---|',
  ].join('\n');
}

function section(title, items) {
  if (items.length === 0) return `## ${title}\n\n_(none)_\n`;
  return `## ${title}\n\n${tableHeader()}\n${items.map(rowFor).join('\n')}\n`;
}

function byLaneSection(handoffs) {
  const active = handoffs.filter(h =>
    ['open', 'claimed', 'in_progress'].includes(h.status)
  );
  if (active.length === 0) return '## By Lane (active)\n\n(no active handoffs)\n';
  const groups = new Map();
  for (const h of active) {
    const lane = h.lane || h.assigned_to || '—';
    if (!groups.has(lane)) groups.set(lane, []);
    groups.get(lane).push(h);
  }
  const laneNames = [...groups.keys()].sort();
  let out = '## By Lane (active)\n\n';
  for (const lane of laneNames) {
    const list = groups.get(lane);
    out += `**${lane}** (${list.length})\n`;
    for (const h of list) {
      const id = h.id || h.file.replace(/\.md$/, '');
      out += `- [${id}](${h.file}) [${h.severity || '?'}] (${h.status}) — ${h.title || ''}\n`;
    }
    out += '\n';
  }
  return out;
}

// G-024 (H-2026-05-05-016): By Category section — group active handoffs by
// category frontmatter (feature/bugfix/refactor/docs/chore). Backward compat:
// missing → "(uncategorized)" group.

function byCategorySection(handoffs) {
  const active = handoffs.filter(h =>
    ['open', 'claimed', 'in_progress'].includes(h.status)
  );
  if (active.length === 0) return '## By Category (active)\n\n(no active handoffs)\n';
  const groups = new Map();
  for (const h of active) {
    const cat = h.category || '(uncategorized)';
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat).push(h);
  }
  // Sort: real categories alphabetical, "(uncategorized)" last
  const catNames = [...groups.keys()].sort((a, b) => {
    if (a === '(uncategorized)') return 1;
    if (b === '(uncategorized)') return -1;
    return a.localeCompare(b);
  });
  let out = '## By Category (active)\n\n';
  for (const cat of catNames) {
    const list = groups.get(cat);
    out += `**${cat}** (${list.length})\n`;
    for (const h of list) {
      const id = h.id || h.file.replace(/\.md$/, '');
      out += `- [${id}](${h.file}) [${h.severity || '?'}] (${h.status}) — ${h.title || ''}\n`;
    }
    out += '\n';
  }
  return out;
}

// G-010 (H-2026-05-05-012): By Project section — group handoffs by project_id frontmatter.
// Backward compat: handoffs without project_id → "(no project)" group.

function byProjectSection(handoffs) {
  const active = handoffs.filter(h =>
    ['open', 'claimed', 'in_progress'].includes(h.status)
  );
  if (active.length === 0) return '## By Project (active)\n\n(no active handoffs)\n';
  const groups = new Map();
  for (const h of active) {
    const project = h.project_id || '(no project)';
    if (!groups.has(project)) groups.set(project, []);
    groups.get(project).push(h);
  }
  // Sort: real project_ids first (alphabetical), "(no project)" last
  const projectNames = [...groups.keys()].sort((a, b) => {
    if (a === '(no project)') return 1;
    if (b === '(no project)') return -1;
    return a.localeCompare(b);
  });
  let out = '## By Project (active)\n\n';
  for (const project of projectNames) {
    const list = groups.get(project);
    out += `**${project}** (${list.length})\n`;
    for (const h of list) {
      const id = h.id || h.file.replace(/\.md$/, '');
      out += `- [${id}](${h.file}) [${h.severity || '?'}] (${h.status}) — ${h.title || ''}\n`;
    }
    out += '\n';
  }
  return out;
}

function render(handoffs) {
  const groups = {
    open: [],
    in_progress: [],
    done: [],
    verified: [],
    wontfix: [],
    other: [],
  };
  for (const h of handoffs) {
    const s = (h.status || '').toLowerCase();
    if (s === 'open') groups.open.push(h);
    else if (s === 'claimed' || s === 'in_progress') groups.in_progress.push(h);
    else if (s === 'done') groups.done.push(h);
    else if (s === 'verified') groups.verified.push(h);
    else if (s === 'wontfix' || s === "won't fix") groups.wontfix.push(h);
    else groups.other.push(h);
  }

  const totals = `> **Counts** · open=${groups.open.length} · in_progress=${groups.in_progress.length} · done=${groups.done.length} · verified=${groups.verified.length} · wontfix=${groups.wontfix.length}`;

  const parts = [
    HEADER,
    '',
    '# Handoffs Index',
    '',
    '> Auto-generated by `scripts/handoffs-index.js` from `H-*.md` frontmatter. Edits are overwritten by the pre-commit hook.',
    '',
    totals,
    '',
    section('Open', groups.open),
    section('In Progress (claimed / in_progress)', groups.in_progress),
    section('Done (awaiting verification)', groups.done),
    section('Verified', groups.verified),
    section("Won't Fix", groups.wontfix),
    byLaneSection(handoffs),
    byProjectSection(handoffs),
    byCategorySection(handoffs),
  ];

  if (groups.other.length > 0) {
    parts.push(section('Other / Unknown status', groups.other));
  }

  return parts.join('\n').trimEnd() + '\n';
}

// ── main

const args = process.argv.slice(2);
const checkMode = args.includes('--check');
const stdoutMode = args.includes('--stdout');

const handoffs = loadHandoffs();
// G-009: collision detection across active + archive (may exit 1)
const allRecursive = loadAllHandoffsRecursive(HANDOFFS_DIR);
detectCollisions(allRecursive);
const next = render(handoffs);

if (stdoutMode) {
  process.stdout.write(next);
  process.exit(0);
}

if (checkMode) {
  const current = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, 'utf8') : '';
  if (current === next) {
    process.exit(0);
  }
  console.error('[handoffs-index] INDEX.md is out of date. Run: node scripts/handoffs-index.js');
  process.exit(1);
}

writeFileSync(INDEX_PATH, next);
console.log(`[handoffs-index] wrote ${relative(REPO_ROOT, INDEX_PATH)} (${handoffs.length} handoffs)`);
