#!/usr/bin/env node
// specs-index — regenerate .olym/specs/_index.md from spec.md frontmatter
//
// Usage:
//   node scripts/specs-index.mjs           # write _index.md
//   node scripts/specs-index.mjs --check   # exit 1 if _index.md drifted (CI / pre-commit)
//   node scripts/specs-index.mjs --stdout  # print to stdout, don't write
//
// Reads:  .olym/specs/**/*.md  (frontmatter)
// Writes: .olym/specs/_index.md
//
// Frontmatter schema (per protocol/spec-discipline.md §3):
//   type, spec_id, version, status, created, updated, owner, audit_dimension
//
// Backward compat: spec_id missing → falls back to relative path stem.
//                  version missing → "?" (legacy specs pre-2026-05-03).
//                  status missing → "draft".
//
// Sections produced:
//   Counts  ·  Active  ·  Draft  ·  Shipped  ·  Archived  ·  By Audit Dimension  ·  By Lifecycle (G-018)

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const SPECS_DIR = join(REPO_ROOT, '.olym', 'specs');
const INDEX_PATH = join(SPECS_DIR, '_index.md');

const HEADER = '<!-- AUTO-GENERATED by scripts/specs-index.mjs · do not edit -->';

// ── frontmatter parser (keeps parity with handoffs-index.js + supports `|` literal blocks for superseded_check)

function parseFrontmatter(text) {
  const trimmed = text.replace(/^﻿/, '');
  const m = trimmed.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const body = m[1];
  const out = {};
  let currentKey = null;
  let literalBlock = null; // { key, indent, lines }
  for (const rawLine of body.split(/\r?\n/)) {
    // Literal block continuation (YAML | style)
    if (literalBlock) {
      const indentMatch = rawLine.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1].length : 0;
      if (rawLine.trim() === '' || indent >= literalBlock.indent) {
        literalBlock.lines.push(rawLine.slice(literalBlock.indent));
        continue;
      }
      out[literalBlock.key] = literalBlock.lines.join('\n').trimEnd();
      literalBlock = null;
    }
    const line = rawLine.replace(/^\s*#.*$/, '');
    if (!line.trim()) continue;
    // List item under currentKey
    const listMatch = line.match(/^\s+-\s+(.*)$/);
    if (listMatch && currentKey) {
      if (!Array.isArray(out[currentKey])) out[currentKey] = [];
      out[currentKey].push(stripQuotes(listMatch[1].trim()));
      continue;
    }
    // key: value
    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*)$/);
    if (kvMatch) {
      const key = kvMatch[1];
      const value = stripQuotes(kvMatch[2].trim());
      if (value === '|') {
        // YAML literal block — capture until dedent
        const probeIndent = 2; // assume standard 2-space child indent
        literalBlock = { key, indent: probeIndent, lines: [] };
        currentKey = null;
      } else if (value === '') {
        out[key] = []; // empty → list to follow
        currentKey = key;
      } else {
        out[key] = value;
        currentKey = null;
      }
    }
  }
  if (literalBlock) {
    out[literalBlock.key] = literalBlock.lines.join('\n').trimEnd();
  }
  return out;
}

function stripQuotes(s) {
  if (s.startsWith('"') && s.endsWith('"')) return s.slice(1, -1);
  if (s.startsWith("'") && s.endsWith("'")) return s.slice(1, -1);
  return s;
}

// ── walk specs dir
// Rule: a "spec" is either
//   - a top-level .md file directly under .olym/specs/ (e.g., architecture-unification.md), OR
//   - a file named exactly "spec.md" anywhere under .olym/specs/ (handles nested e.g. marketing-v2/test/gologin/spec.md)
// Anything else (chapter docs, READMEs, design.md, requirements.md) is excluded — it's not a spec, it's a sub-document.

function walkSpecs(dir, baseDir = dir, depth = 0) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('_')) continue; // skip _index.md, _archive/, _template.md
    const full = join(dir, entry.name);
    const rel = relative(baseDir, full).split(sep).join('/');
    if (entry.isDirectory()) {
      out.push(...walkSpecs(full, baseDir, depth + 1));
    } else if (entry.name.endsWith('.md')) {
      // Top-level .md (depth=0) → always include
      // Nested .md → only if filename === 'spec.md'
      if (depth === 0 || entry.name === 'spec.md') {
        out.push({ full, rel });
      }
    }
  }
  return out;
}

function normalizeVersion(v) {
  if (!v || v === '?') return '?';
  // Strip leading "v" / "V" if present so display is consistent — render adds a single "v" prefix
  return String(v).replace(/^v/i, '');
}

function loadSpecs() {
  const files = walkSpecs(SPECS_DIR);
  const specs = [];
  const missing = []; // .md files with no YAML frontmatter — pending migration to spec-discipline §3
  for (const { full, rel } of files) {
    const text = readFileSync(full, 'utf8');
    const fm = parseFrontmatter(text);
    if (!fm) {
      missing.push({ file: rel });
      continue;
    }
    // Defaults / fallbacks
    const id = fm.spec_id || rel.replace(/\/spec\.md$/, '').replace(/\.md$/, '');
    const version = normalizeVersion(fm.version);
    const status = (fm.status || 'draft').toLowerCase();
    const dim = fm.audit_dimension || '—';
    const owner = fm.owner || '—';
    const created = fm.created || '—';
    const updated = fm.updated || fm.created || '—';
    const lifecycle = fm.lifecycle || null;
    specs.push({
      file: rel,
      id,
      version,
      status,
      audit_dimension: dim,
      type: fm.type || '—',
      owner,
      created,
      updated,
      lifecycle,
    });
  }
  specs.sort((a, b) => a.id.localeCompare(b.id));
  missing.sort((a, b) => a.file.localeCompare(b.file));
  return { specs, missing };
}

// ── render

function rowFor(s) {
  const link = `[${s.id}](${s.file})`;
  const ver = s.version === '?' ? '?' : `v${s.version}`;
  return `| ${link} | ${ver} | ${s.status} | ${s.audit_dimension} | ${s.owner} | ${s.updated} |`;
}

function tableHeader() {
  return [
    '| spec_id | version | status | audit_dimension | owner | updated |',
    '|---|---|---|---|---|---|',
  ].join('\n');
}

function section(title, items) {
  if (items.length === 0) return `## ${title}\n\n_(none)_\n`;
  return `## ${title}\n\n${tableHeader()}\n${items.map(rowFor).join('\n')}\n`;
}

function byAuditDimensionSection(specs) {
  const active = specs.filter(s => s.status === 'active' || s.status === 'draft');
  if (active.length === 0) return '## By Audit Dimension (active + draft)\n\n_(none)_\n';
  const groups = new Map();
  for (const s of active) {
    const dim = s.audit_dimension || '—';
    // audit_dimension may be comma-separated — split
    const dims = dim.split(',').map(d => d.trim()).filter(Boolean);
    const keys = dims.length > 0 ? dims : ['—'];
    for (const k of keys) {
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k).push(s);
    }
  }
  const keys = [...groups.keys()].sort();
  let out = '## By Audit Dimension (active + draft)\n\n';
  for (const k of keys) {
    const list = groups.get(k);
    out += `**${k}** (${list.length})\n`;
    for (const s of list) {
      const ver = s.version === '?' ? '?' : `v${s.version}`;
      out += `- [${s.id}](${s.file}) ${ver} (${s.status})\n`;
    }
    out += '\n';
  }
  return out;
}

function byLifecycleSection(specs) {
  // G-018: group active + draft specs by lifecycle (alpha/beta/GA), backward compat (unspecified) last.
  const active = specs.filter(s => s.status === 'active' || s.status === 'draft');
  if (active.length === 0) return '## By Lifecycle (active + draft)\n\n_(none)_\n';
  const groups = new Map();
  for (const s of active) {
    const key = s.lifecycle || '(unspecified)';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(s);
  }
  // Order: alpha, beta, GA, then any other, then (unspecified) last.
  const known = ['alpha', 'beta', 'GA'];
  const keys = [...groups.keys()].sort((a, b) => {
    if (a === '(unspecified)') return 1;
    if (b === '(unspecified)') return -1;
    const ai = known.indexOf(a);
    const bi = known.indexOf(b);
    if (ai === -1 && bi === -1) return a.localeCompare(b);
    if (ai === -1) return 1;
    if (bi === -1) return -1;
    return ai - bi;
  });
  let out = '## By Lifecycle (active + draft)\n\n';
  for (const k of keys) {
    const list = groups.get(k);
    out += `**${k}** (${list.length})\n`;
    for (const s of list) {
      const ver = s.version === '?' ? '?' : `v${s.version}`;
      out += `- [${s.id}](${s.file}) ${ver} (${s.status})\n`;
    }
    out += '\n';
  }
  return out;
}

function render({ specs, missing }) {
  const groups = {
    active: [],
    draft: [],
    shipped: [],
    archived: [],
    other: [],
  };
  for (const s of specs) {
    if (groups[s.status]) groups[s.status].push(s);
    else groups.other.push(s);
  }

  const totals = `> **Counts** · active=${groups.active.length} · draft=${groups.draft.length} · shipped=${groups.shipped.length} · archived=${groups.archived.length}` +
    (groups.other.length ? ` · other=${groups.other.length}` : '') +
    (missing.length ? ` · **missing-frontmatter=${missing.length}**` : '');

  const parts = [
    HEADER,
    '',
    '# Specs Index',
    '',
    '> Auto-generated by `scripts/specs-index.mjs` from `spec.md` frontmatter. Edits are overwritten by pre-commit hook.',
    '> Discipline: [.olym/steering/protocol/spec-discipline.md](../steering/protocol/spec-discipline.md)',
    '',
    totals,
    '',
    section('Active', groups.active),
    section('Draft', groups.draft),
    section('Shipped', groups.shipped),
    section('Archived', groups.archived),
    byAuditDimensionSection(specs),
    byLifecycleSection(specs),
  ];

  if (groups.other.length > 0) {
    parts.push(section('Other / Unknown status', groups.other));
  }

  if (missing.length > 0) {
    parts.push('## Missing Frontmatter (pending migration to spec-discipline §3)\n');
    for (const m of missing) {
      parts.push(`- [${m.file}](${m.file})`);
    }
    parts.push('');
  }

  return parts.join('\n').trimEnd() + '\n';
}

// ── main

const args = process.argv.slice(2);
const checkMode = args.includes('--check');
const stdoutMode = args.includes('--stdout');

const result = loadSpecs();
const output = render(result);

if (stdoutMode) {
  process.stdout.write(output);
  process.exit(0);
}

if (checkMode) {
  const existing = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, 'utf8') : '';
  if (existing !== output) {
    process.stderr.write(
      `[specs-index] DRIFT: .olym/specs/_index.md is stale.\n` +
      `Run: node scripts/specs-index.mjs\n`
    );
    process.exit(1);
  }
  process.stdout.write('[specs-index] _index.md up to date.\n');
  process.exit(0);
}

writeFileSync(INDEX_PATH, output, 'utf8');
const summary = `${result.specs.length} specs` +
  (result.missing.length ? ` (+${result.missing.length} missing frontmatter)` : '');
process.stdout.write(`[specs-index] Wrote ${relative(REPO_ROOT, INDEX_PATH)} (${summary}).\n`);
